version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: adsquare_tic-tac-toe_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=adsquare
    ports:
      - "5442:5432"
