package com.example.tictactoe.entity;

import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;

import java.time.ZonedDateTime;

@Getter
@MappedSuperclass
@EqualsAndHashCode
public abstract class AbstractEntity {
    @Id
    @Setter(AccessLevel.PROTECTED) /* does not expose the setter outside this class, its autogenerated by Postgres*/
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private long id;

    @Column(name = "created_date")
    @CreatedDate
    private ZonedDateTime createdDate;
}
